api/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('signup/', views.SignUpApiView.as_view(), name='sign_up_api'),
    path('token/', views.CustomObtainAuthToken.as_view(), name='token'),
    path('user_cars/', views.UserCarsApiView.as_view(), name='user_cars'),
    path('all_users/', views.AllUsersApiView.as_view(), name='all_users'),
    path('me/', views.MeApiView.as_view(), name='me'),
]

cars/urls.py
from django.urls import path, include
from django.views import generic

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('rent/', views.CarsView.as_view(), name='rent'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('add_car/', views.AddCarView.as_view(), name='add_car'),
    ]

rent_car/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from rent_car import settings

handler404 = 'cars.errors.page_not_found'
handler500 = 'cars.errors.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/v1/', include('api.urls')),
    path('', include('cars.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

cars/models.py
import datetime

from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

YEARS = [
    (year, year) for year in range(1990, datetime.date.today().year+1)
]


class Car(models.Model):
    title = models.CharField(max_length=255,
                             blank=False, verbose_name='Название')
    title_en = models.CharField(max_length=255,
                                blank=True, null=True,
                                verbose_name='Название на английском')
    prod_year = models.IntegerField(choices=YEARS,
                                    verbose_name='Год производства')
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name='Создано')
    owner = models.ForeignKey(to=User,
                              on_delete=models.CASCADE,
                              related_name='car',
                              verbose_name='Владелец')

    class Meta:
        verbose_name = 'Автомобиль'
        verbose_name_plural = 'Автомобили'

    def __str__(self):
        return f'Автомобиль {self.title}({self.title_en}) {self.prod_year}' \
               f' года производства.'


class RentalPeriod(models.Model):
    car = models.ForeignKey(to=Car,
                            on_delete=models.CASCADE,
                            related_name='rental_period',
                            verbose_name='Автомобиль')
    driver = models.ForeignKey(to=User,
                               on_delete=models.CASCADE,
                               related_name='rental_period',
                               verbose_name='Водитель')
    start_date = models.DateField(blank=False, null=False,
                                  verbose_name='Дата начала аренды')
    end_date = models.DateField(blank=False, null=False,
                                verbose_name='Дата конца аренды')

    class Meta:
        verbose_name = 'Период аренды'
        verbose_name_plural = 'Периоды аренды'

    def __str__(self):
        return f'Период аренды автомобиля {self.car.title} пользователя' \
               f' {self.driver} с {self.start_date}г. по {self.end_date}г.'

    @property
    def upcoming(self):
        if self.start_date > datetime.date.today():
            return True
        return False

    @property
    def current(self):
        if self.start_date <= datetime.date.today() <= self.end_date:
            return True
        return False

    @property
    def closed(self):
        if datetime.date.today() > self.end_date:
            return True
        return False

cars/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.db.models import Q

from cars import models


class CarForm(forms.ModelForm):
    class Meta:
        model = models.Car
        exclude = ('owner',)


class RentalPeriodForm(forms.ModelForm):
    class Meta:
        model = models.RentalPeriod
        exclude = ('driver',)

    def clean(self):
        super(RentalPeriodForm, self).clean()
        start_date = self.cleaned_data.get('start_date')
        end_date = self.cleaned_data.get('end_date')

        if start_date < datetime.date.today() or end_date < start_date:
            self._errors['start_date'] = self.error_class([
                'Дата начала не может быть меньше сегодня'
            ])
            self._errors['end_date'] = self.error_class([
                'Дата конца не может быть меньше даты начала или сегодня'
            ])
        return self.cleaned_data

    def is_valid(self):
        start_date = self.data['start_date']
        end_date = self.data['end_date']
        car = self.data['car']

        excluded_cars = models.RentalPeriod.objects.filter(
            Q(start_date__range=(start_date, end_date)) |
            Q(end_date__range=(start_date, end_date))
        )
        if car in excluded_cars:
            return False
        return super().is_valid()

cars/views.py
import datetime

from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from cars import forms, models
from rent_car import settings


class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'index.html'


class SuccessView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'misc/success.html'

    def get_context_data(self, **kwargs):
        referer = self.request.META.get('HTTP_REFERER')
        context = super(SuccessView, self).get_context_data(**kwargs)
        if 'add_car' in referer:
            context['success'] = 'Автомобиль добавлен'
            return context
        elif 'rent' in referer:
            context['success'] = 'Автомобиль забронирован'
            return context
        elif 'profile/update' in referer:
            context['success'] = 'Данные профиля обновлены'
            return context
        return context


class CarsView(LoginRequiredMixin, generic.FormView, generic.ListView):
    template_name = 'cars.html'
    form_class = forms.RentalPeriodForm
    success_url = reverse_lazy('success')

    def get(self, request, *args, **kwargs):
        date_format = '%Y-%m-%d'
        start_date = datetime.datetime.strptime(
            self.request.GET.get('start_date'), date_format).date()
        end_date = datetime.datetime.strptime(
            self.request.GET.get('end_date'), date_format).date()
        if start_date < datetime.date.today() >= end_date \
                or start_date > end_date:
            return redirect(to='index')
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        start_date = self.request.GET.get('start_date')
        end_date = self.request.GET.get('end_date')
        excluded_cars = models.RentalPeriod.objects.filter(
            Q(start_date__range=(start_date, end_date)) |
            Q(end_date__range=(start_date, end_date))
        ).values_list('car_id')
        cars = models.Car.objects.exclude(id__in=excluded_cars)
        return cars

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            form.instance.driver = self.request.user
            form.save()
            return self.form_valid(form)
        return self.form_invalid(form)


class AddCarView(LoginRequiredMixin, generic.FormView):
    template_name = 'add_car.html'
    form_class = forms.CarForm
    success_url = reverse_lazy('success')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.save()
        theme = 'Автомобиль добавлен'
        message = f' Автомобиль {form.instance.title} добавлен в систему.'
        send_mail(theme, message, settings.EMAIL_HOST_USER,
                  [self.request.user.email, ], fail_silently=False)
        return super().form_valid(form)

templates/add_car.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
    <div>
    <h1>Введите информацию об автомобиле</h1>
    <form class="card-body" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {% for field in form %}
            <div class="form-control">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
            </div>
        {% endfor %}
            <div class="card-footer">
        <button class="btn btn-primary" type="submit">Добавить автомобиль</button>
    </form>
    </div>
{% endblock content %}
{% block scripts %}
<script src="{% static 'js/datepicker.js' %}"></script>
{% endblock scripts %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.87.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <title>Главная</title>
</head>
<body class="bg-light">
    {% include 'includes/nav.html' %}
    <div class="container">
        <main>
            {% block content %}
                    <!-- Содержимое страницы -->
            {% endblock %}
        </main>
        <footer></footer>
    </div>
{% block javascript %}
    <script src='{% static 'js/jquery-3.1.0.min.js'  %}'></script>
    <script src='{% static 'js/jquery-3.2.1.min.js' %}'></script>
{% endblock javascript %}
{% block scripts %}
{% endblock scripts %}
</body>
</html>

templates/cars.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
        <div>
        <h1>Свободные автомобили на эти даты</h1>
        {% for object in object_list %}
    <form class="card-body" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_car">{{ object }}</label>
        <input class="form-control" id="id_car" type="hidden" name="car" value="{{ object.id }}"/>
        {% if form.errors.car %}
                <ul>{{ form.errors.car }}</ul>
        {% endif %}
        <input class="form-control" id="id_start_date" type="hidden" name="start_date" value="{{ request.GET.start_date }}"/>
        {% if form.errors.start_date %}
                <ul>{{ form.errors.start_date }}</ul>
        {% endif %}
        <input class="form-control" id="id_end_date" type="hidden" name="end_date" value="{{ request.GET.end_date }}"/>
        {% if form.errors.end_date %}
                <ul>{{ form.errors.end_date }}</ul>
        {% endif %}
        <div class="card-footer">
        <button class="btn btn-primary" type="submit">Арендовать</button>
        </div>
    </form>
            {% empty %}
            <h1>К сожалению на эти даты нет свободных автомобилей</h1>
            {% endfor %}
    </div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
    <div>
    <h1>Введите даты аренды</h1>
    <form class="card-body" method="get" action="/rent/">
        <label for="id_start_date">Дата начала</label>
        <input class="form-control" id="id_start_date" type="date" name="start_date" required/>
        <label for="id_end_date">Дата конца</label>
        <input class="form-control" id="id_end_date" type="date" name="end_date" required/>
        <div class="card-footer">
        <button class="btn btn-primary" type="submit">Найти автомобиль</button>
        </div>
    </form>
    </div>
{% endblock content %}
{% block scripts %}
<script src="{% static 'js/datepicker.js' %}"></script>
{% endblock scripts %}

templates/profile.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<div>
    {% if request.path == '/auth/profile/' %}
    <form class="card-body" method="get" action="/auth/profile/update/">
    {% elif request.path == '/auth/profile/update/' %}
    <form class="card-body" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% endif %}
        {% for field in form %}
            <div class="form-control">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
            </div>
        {% endfor %}
            <div class="card-footer">
         {% if request.path == '/auth/profile/' %}
        <button class="btn btn-primary" type="submit">Изменить информацию</button>
         {% elif request.path == '/auth/profile/update/' %}
        <button class="btn btn-primary" type="submit">Сохранить</button>
         {% endif %}
    </div>
</div>
{% endblock %}